permalink: pretty
sass:
  style: compressed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

paginate: 5

title: Simple Jekyll Theme
author: John Doe
tagline: "My personal blog"
description: "A blog of awesome stuff"
url: "https://johndoe.github.io"
lang: en

fontawesome-kit-id: xxxxx
# google-tag-manager-id: xxxxxxx

feed:
  posts_limit: 10

defaults:
  -
    scope:
      path: "assets/images/*"
    values:
      sitemap: false
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      category: posts
      toc: true

exclude:
  - Gemfile
  - Rakefile
  - yarn.lock
  - pre-commit
  - /*.json
  - /*.gemspec
  - /*.gem
