permalink: pretty
sass:
  style: compressed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

title: Simple
author: W Zhang
tagline: "A minimalistic theme for blogs"
description: "Theme for my personal blog https://weixuanz.github.io"
url: "https://weixuanz.github.io/simple-jekyll-theme"
lang: en

# Optional
# google-tag-manager-id: GTM-xxxxxx
# font-awesome-kit: xxxxxxxxx  # using Font Awesome Kit instead of defining svg icons

paginate: 5

feed:
  posts_limit: 10

navigation:
  - name: Home
    link: /
  - name: About
    link: /about/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      category: posts
      toc: true

exclude:
  - Gemfile
  - Rakefile
  - yarn.lock
  - pre-commit
  - /*.json
  - /*.gemspec
  - /*.gem
