permalink: pretty
sass:
  style: compressed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

title: Simple Jekyll Theme
author: W Zhang
tagline: "A minimalistic theme for blogs"
description: "Theme for my personal blog https://weixuanz.github.io"
url: "https://weixuanz.github.io/simple-jekyll-theme"
lang: en

fontawesome-kit-id: xxxxxxxxxx
# google-tag-manager-id: GTM-xxxxxx

paginate: 5

feed:
  posts_limit: 10

navigation:
  - name: Home
    link: /
  - name: About
    link: /about/

defaults:
  -
    scope:
      path: "assets/images/*"
    values:
      sitemap: false
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      category: posts
      toc: true

exclude:
  - Gemfile
  - Rakefile
  - yarn.lock
  - pre-commit
  - /*.json
  - /*.gemspec
  - /*.gem
